### ISSUE TITLE
Configurable Rectangle Shape

### ISSUE THREAD

**Issue by NickAtGit** [benedom/SwiftyCrop#15]
The package looks interesting, thanks for making it. But so far I'm just seeing circle and square as shapes. I would like to pass the width and height to the package to define my rectangle. Are there any technical limitations why you didn't build that?

**Comment by benedom** [comment]
Hi, the reason for this is that those are the most commonly used shapes when cropping images. When I built this library, the requirements were for these shapes only.
There is already an issue that connects to your question: https://github.com/benedom/SwiftyCrop/issues/12

I tried working on it but had to pause development due to time constraints. The cropping needs to be adjusted with a new calculation of the cropping area, which is a bit complicated.

Feel free to take over the issue if you want and submit a PR if you manage to build it!
